name: 1 - Worflow connexion Azure # Nom du Workflow

on: # declenchement du workflows
  workflow_dispatch: # manuel https://docs.github.com/en/actions/using-workflows/triggering-a-workflow

jobs:

  connexion-azure: # Nom du job
    runs-on: ubuntu-latest # Runner machine quio execute le workflow

  steps:

  - name: connexion Azure 
    uses: Azure/login@v1 # Action pour se connecter Ã  Azure https://github.com/Azure/login
    with:
      creds: ${{ secrets.AZURE_CREDENTIALS }} # Service Secrets de GitHub https://docs.github.com/en/actions/security-guides/encrypted-secrets

  - name: Liste des ressources groupes dans un abonnement
    run: |
      az group list -o table
      